#!/bin/sh

set -e

case "$1" in
  configure)
    systemd-sysusers /usr/lib/sysusers.d/pint.conf
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    :
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
