name: Check go.mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Run go mod tidy
        run: go mod tidy

      - name: Check for local changes
        run: git diff --exit-code
